local Animations = {
	Pickup = {
		Id = "rbxassetid://79572442068277", -- --99451166392598, 116164294403501
		Priority = Enum.AnimationPriority.Action3,
		Loop = false,
	},
	
	PickupTree = {
		Id = "rbxassetid://116164294403501",
		Priority = Enum.AnimationPriority.Action,
		Loop = false,
	},
	
	PickupLeft = {
		Id = "rbxassetid://82228869389097",
		Priority = Enum.AnimationPriority.Action3,
		Loop = false,
	},
	
	AxeHold = {
		Id = "rbxassetid://129765606580363",
		Priority = Enum.AnimationPriority.Action,
		Loop = true,
	},

	AxeSwing = {
		Id = "rbxassetid://83020699345183",
		Priority = Enum.AnimationPriority.Action2,
		Loop = false,
	},
}

return Animations
