local Items = {
	["example"] = {
		["Name"] = "item1",
		["Type"] = "resource, crop, furniture, tool",
		["SellPrice"] = 100,
		["StackLimit"] = 16,
		["Rarity"] = "basic, rare, mythic",
		["IconId"] = "1232145125"
	},
	["1"] = {
		Name = "Wood",
		Type = "resource",
		SellPrice = 3,
		StackLimit = 32,
		Rarity = "basic",
		IconId = "rbxassetid://107979940945908"
	},
	
	["2"] = {
		Name = "Stick",
		Type = "resource",
		SellPrice = 3,
		StackLimit = 64,
		Rarity = "basic",
		IconId = "rbxassetid://94544670291181"
	},
	
	["3"] = {
		Name = "Stone",
		Type = "resource",
		SellPrice = 3,
		StackLimit = 32,
		Rarity = "basic",
		IconId = "rbxassetid://118467313131897"
	},
	
	["600"] = {
		Name = "Makeshift Axe",
		Type = "tool",
		SellPrice = 15,
		StackLimit = 1,
		Rarity = "basic",
		IconId = "rbxassetid://137435185968932",
		ToolId = "MakeshiftAxe"
	},
	
}

return Items
